# Generated by Django 2.1.5 on 2019-02-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_text', models.TextField()),
            ],
        ),
    ]
