# Generated by Django 2.1.5 on 2019-02-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intray', '0002_auto_20190203_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_text',
            field=models.TextField(editable=False),
        ),
    ]
