# Generated by Django 2.1.5 on 2019-02-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intray', '0003_auto_20190203_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_text',
            field=models.TextField(),
        ),
    ]
