# Generated by Django 2.1.5 on 2019-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intray', '0004_auto_20190203_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
